resources:
  - name: govwifi-admin
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-admin.git"
      branch: "concourse"

jobs:
  - name: lint & test
    plan:
      - get: govwifi-admin
        trigger: true
      - task: lint
        privileged: true
        file: govwifi-admin/ci/tasks/lint.yml
      - task: test
        privileged: true
        file: govwifi-admin/ci/tasks/test.yml
