resources:
  - name: govwifi-admin
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-admin.git"
      branch: "concourse"

jobs:
  - name: runner-image
    plan:
      - get: govwifi-admin
        trigger: true
      - task: build
        privileged: true
        file: govwifi-admin/ci/tasks/runner-image.yml
