resources:
  - name: govwifi-admin
    type: git
    source:
      uri: "https://github.com/alphagov/govwifi-admin.git"
      branch: "concourse"

  - name: ecr
    # This needs to be docker-image, until registry-image supports ECR
    type: docker-image
    source:
      repository: "((ecs-registry))/govwifi/admin"
      tag: concourse-latest
      aws_access_key_id: ((ecr-access-key-id))
      aws_secret_access_key: ((ecr-secret-access-key))

  - name: runner
    # See https://github.com/alphagov/govwifi-concourse-runner for a reference dockerfile
    # readonly_private_ecr_repo_url is provided by the hosted Concourse
    type: registry-image
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: concourse-runner-latest

  - name: mysql-image
    type: registry-image
    source:
      repository: mysql
      tag: 5.7

  - name: ruby-image
    type: registry-image
    source:
      repository: ruby
      tag: 2.6.2-alpine3.9

  - name: nginx-image
    type: registry-image
    source:
      repository: nginx
      tag: alpine

groups:
  - name: test
    jobs: [lint & test]
  - name: push
    jobs: [Push Image]
  - name: staging
    jobs:
      - migrate staging
      - deploy staging
  - name: production
    jobs:
      - production gate
      - migrate production
      - deploy production

jobs:
  - name: lint & test
    plan:
      - aggregate:
        - get: govwifi-admin
          trigger: true
        - get: mysql-image
          params: {format: oci}
        - get: ruby-image
          params: {format: oci}
        - get: nginx-image
          params: {format: oci}
        - get: runner
      - task: pre-build
        privileged: true
        image: runner
        file: govwifi-admin/ci/tasks/pre-build.yml
      - aggregate:
        - task: lint
          privileged: true
          image: runner
          file: govwifi-admin/ci/tasks/lint.yml
        - task: test
          privileged: true
          image: runner
          file: govwifi-admin/ci/tasks/test.yml
  - name: Push Image
    plan:
      - get: govwifi-admin
        trigger: true
        passed: ['lint & test']
      - put: ecr
        params:
          build: govwifi-admin
          build_args:
            BUNDLE_INSTALL_FLAGS: '--without test development'
  - name: migrate staging
    plan:
      - get: govwifi-admin
        trigger: true
        passed: ['Push Image']
      - task: 'migrate'
        image: runner
        file: govwifi-admin/ci/tasks/migrate.yml
        params:
          DEPLOY_STAGE: staging
          AWS_ACCESS_KEY_ID: ((deploy-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((deploy-secret-access-key))
          AWS_DEFAULT_REGION: ((deploy-region))
  - name: deploy staging
    plan:
      - get: govwifi-admin
        trigger: true
        passed: ['migrate staging']
      - task: 'deploy staging'
        image: runner
        file: govwifi-admin/ci/tasks/deploy.yml
        params:
          DEPLOY_STAGE: staging
          AWS_ACCESS_KEY_ID: ((deploy-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((deploy-secret-access-key))
          AWS_DEFAULT_REGION: ((deploy-region))
  - name: production gate
    plan:
      - get: govwifi-admin
        passed: [deploy staging]
  - name: migrate production
    plan:
      - get: govwifi-admin
        trigger: true
        passed: ['production gate']
      - task: 'migrate'
        image: runner
        file: govwifi-admin/ci/tasks/migrate.yml
        params:
          DEPLOY_STAGE: production
          AWS_ACCESS_KEY_ID: ((deploy-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((deploy-secret-access-key))
          AWS_DEFAULT_REGION: ((deploy-region))
  - name: deploy production
    plan:
      - get: govwifi-admin
        trigger: true
        passed:
          - migrate production
      - task: 'deploy staging'
        image: runner
        file: govwifi-admin/ci/tasks/deploy.yml
        params:
          DEPLOY_STAGE: production
          AWS_ACCESS_KEY_ID: ((deploy-access-key-id))
          AWS_SECRET_ACCESS_KEY: ((deploy-secret-access-key))
          AWS_DEFAULT_REGION: ((deploy-region))
