version: '3.4'

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    expose:
      - "3306"

  rr_db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_DATABASE: rr_govwifi
    expose:
      - "3306"

  govuk-fake-registers:
    build:
      context: govuk_fake_register
    expose:
      - "7000"

  app:
    build:
      context: .
      args:
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    links:
      - db
      - rr_db
    expose:
    - "3000"
    depends_on:
      - 'govuk-fake-registers'
    environment:
      RACK_ENV: development
      DB_USER: root
      DB_PASS: root
      NOTIFY_API_KEY: 'govwifi_admin_development-8a09d848-d453-4aea-bb1e-46f7d19a1814-d2306cbb-39f5-40e5-9f86-1778c2bef6fa'
      DB_HOST: db
      DEVISE_SECRET_KEY: fake-secret-key
      LONDON_RADIUS_IPS: '111.111.111.111,121.121.121.121'
      DUBLIN_RADIUS_IPS: '222.222.222.222,232.232.232.232'
      S3_PUBLISHED_LOCATIONS_IPS_BUCKET: 'StubBucket'
      S3_PUBLISHED_LOCATIONS_IPS_OBJECT_KEY: 'StubKey'
      S3_SIGNUP_WHITELIST_BUCKET: 'StubBucket'
      S3_SIGNUP_WHITELIST_OBJECT_KEY: 'StubKEY'
      S3_WHITELIST_OBJECT_KEY: 'WhitelistStubKey'
      LOGGING_API_SEARCH_ENDPOINT: 'https://govwifi-logging-api.gov.uk/search/'
      S3_MOU_BUCKET: 'StubMouBucket'
      RR_DB_USER: root
      RR_DB_PASS: root
      RR_DB_HOST: rr_db
      RR_DB_NAME: rr_govwifi
