version: '3.4'

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "13306:3306"

  rr_db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_DATABASE: rr_govwifi
    ports:
      - "13307:3306"

  fake-registers:
    build:
      context: fake_register
    ports:
      - "7000:7000"

  app:
    build: .
    links:
      - rr_db
    ports:
    - "8080:3000"
    depends_on:
      - 'fake-registers'
