version: '3.4'

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "13306:3306"

  app:
    build: .
    ports:
    - "8080:3000"
