---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/builder-task

params:
  REPOSITORY: govwifi/admin
  TAG: latest
  CONTEXT: govwifi-admin

inputs:
  - name: govwifi-admin

outputs:
  - name: deployment-image

caches:
  - path: cache

run:
  path: build
