---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cybojenix/govwifi-concourse-runner

inputs:
  - name: govwifi-admin

params:
  DEPLOY_STAGE: ((deploy_stage))
  AWS_ACCESS_KEY_ID: ((aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
  AWS_DEFAULT_REGION: ((aws-region))

run:
  path: govwifi-admin/ci/tasks/scripts/migrate.sh
