---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/builder-task

params:
  REPOSITORY: govwifi/runner
  CONTEXT: govwifi-admin/ci/dockerfiles/runner

inputs:
  name: govwifi-admin

outputs:
- name: image

caches:
  - path: cache

run:
  path: build
