mysql: &mysql
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>

test:
  <<: *mysql
  database: govwifi_admin_test

development:
  <<: *mysql
  database: development

staging:
  <<: *mysql
  database: govwifi_admin_staging

production:
  <<: *mysql
  database: govwifi_admin_production
