staging:
  support_email: 'dev@localhost.com'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  notify_support_of_new_user:
    template_id: '79af3335-ab32-4c4b-9075-b9d7138c7e61'
  reset_password_email:
    template_id: '1672af2e-2acb-463a-95ee-2adad2aaceee'
  invite_email:
    template_id: 'e3b5ca96-9164-462f-a0b0-65d2103c1ab8'
  help_email:
    template_id: '152cf3ff-e0e2-4f41-9ba0-28091db3f37f'
  unlock_account:
    template_id: '41f8744a-ebe0-417e-98c7-09002ff17a95'

development:
  support_email: 'dev@localhost.com'
  confirmation_email:
    template_id: '1af17502-9797-4e61-904e-999f6cf259a5'
  notify_support_of_new_user:
    template_id: '79af3335-ab32-4c4b-9075-b9d7138c7e61'
  reset_password_email:
    template_id: '1672af2e-2acb-463a-95ee-2adad2aaceee'
  invite_email:
    template_id: 'e3b5ca96-9164-462f-a0b0-65d2103c1ab8'
  help_email:
    template_id: '152cf3ff-e0e2-4f41-9ba0-28091db3f37f'
  unlock_account:
    template_id: '41f8744a-ebe0-417e-98c7-09002ff17a95'

test:
  support_email: 'test@localhost'
  confirmation_email:
    template_id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  notify_support_of_new_user:
    template_id: 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'
  reset_password_email:
    template_id: 'zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz'
  invite_email:
    template_id: 'wwwwwwww-wwww-wwww-wwww-wwwwwwwwwwww'
  help_email:
    template_id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee'
  unlock_account:
    template_id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'

production:
  support_email: 'govwifi-support@digital.cabinet-office.gov.uk'
  confirmation_email:
    template_id: '5f42e490-ce5e-44e7-9104-805136961116'
  notify_support_of_new_user:
    template_id: 'fd79c7b9-48d7-4086-b62a-0fc6f56daa4b'
  reset_password_email:
    template_id: '63f566f6-8ae8-4356-9baa-cb4c3c0a6671'
  invite_email:
    template_id: '21b73fa7-8149-4778-8cba-46287bbfecc5'
  help_email:
    template_id: '5afffbbc-dbbf-4f50-b29d-8d058eb51734'
  unlock_account:
    template_id: '39465eec-632a-4475-82ac-4bd8a45386ea'

