default: &default
  end_user_docs_link: 'https://www.gov.uk/government/collections/connect-to-govwifi'
  end_user_troubleshooting_link: 'https://www.gov.uk/guidance/solve-problems-with-connecting-to-govwifi'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  product_page_link: 'https://wifi.service.gov.uk'
  google_tag_container_ID: 'GTM-TNHHHPZ'
  registers_url: 'https://government-organisation.register.gov.uk'

development:
  <<: *default
  registers_url: 'http://govuk-fake-registers:7000'

test:
  <<: *default

staging:
  google_analytics_script_id: 'UA-127779891-2'

  <<: *default

production:
  google_analytics_script_id: 'UA-127779891-1'
  <<: *default
