default: &default
  end_user_docs_link: 'https://wifi.service.gov.uk/connect.html'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  product_page_link: 'https://wifi.service.gov.uk'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
