default: &default
  end_user_docs_link: 'https://wifi.service.gov.uk/connect'
  end_user_troubleshooting_link: 'https://wifi.service.gov.uk/troubleshooting'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  product_page_link: 'https://wifi.service.gov.uk'
  google_tag_container_ID: 'GTM-TNHHHPZ'

development:
  <<: *default

test:
  <<: *default

staging:
  google_analytics_script_id: 'UA-127779891-2'

  <<: *default

production:
  google_analytics_script_id: 'UA-127779891-1'
  <<: *default
