default: &default
  end_user_docs_link: 'https://wifi.service.gov.uk/connect.html'
  end_user_troubleshooting_link: 'https://wifi.service.gov.uk/troubleshooting.html'
  organisation_docs_link: 'https://docs.wifi.service.gov.uk'
  product_page_link: 'https://wifi.service.gov.uk'
  organisation_troubleshooting_link: 'https://docs.wifi.service.gov.uk/troubleshooting.html#troubleshooting'

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
